AllCops:
  Include:
    - Rakefile
    - Gemfile
    - '*.gemspec'
  Exclude:
    - 'gemfiles/vendor/**/*'

# Broadly speaking, test code gets a pass for most of the Metrics family.
#
# IMO test code is not the place get pedantic about class length,
# method complexity, etc.  One should be encouraged to add more tests
# with minimal friction, not forced to make a hard choice between
# cutting tests or splitting up my test suites.
#
Metrics/BlockLength:
  Exclude:
    - 'test/**/*.rb'
Metrics/ClassLength:
  Max: 400
  Exclude:
    - 'test/**/*.rb'

# I like this Metric in principle, but I don't like the default max of
# 15.
#
# Also, as per Metrics/ClassLength IMO this kind of limit should not
# apply to test code (I get up to 318 over there).
#
Metrics/AbcSize:
  Max: 30
  Exclude:
    - 'test/**/*.rb'

# I like this Metric in principle, but I don't like the default max of
# 10.
#
# Also, as per Metrics/ClassLength IMO this kind of limit should not
# apply to test code.
#
Metrics/MethodLength:
  Max: 50
  Exclude:
    - 'test/**/*.rb'

# I put extra spaces in a lot of expressions for a lot of different
# reasons, including especially readability.
#
# I reject these cops.
#
Layout:
  Enabled: false

# As a group, the Style cops are bewilderingly opiniated.
#
# In some cases IMO they are harmful e.g. Style/TernaryParentheses.
#
# I reject these cops.
#
Style:
  Enabled: false

# I like a lot of the Lint tests, but not these.
#
Lint/AmbiguousBlockAssociation:           # obnoxiously rejects idiomatic Ruby
  Enabled: false

# Naming/FileName is kind of cool but off-base w/r/t demanding that
# Appraisals use snake_case.
#
Naming/FileName:
  Exclude:
    - Appraisals
