AllCops:
  Include:
    - Rakefile
    - Gemfile
    - '*.gemspec'
  Exclude:
    - 'gemfiles/vendor/**/*'

# Some classes and methods need to be big.
#
# I'll break them down for testability or composability or
# applicability, but not because I crossed an invisible line that
# somebody made up.
#
Metrics:
  Enabled: false

# I put extra spaces in a lot of expressions for a lot of different
# reasons, including especially readability.
#
Layout:
  Enabled: false

# As a group, the Style cops are bewilderingly opiniated.
#
# In some cases IMO they are actively harmful e.g. Style/TernaryParentheses.
#
# I reject these cops.
#
Style:
  Enabled: false

# I like a lot of the Lint tests, but not these.
#
Lint/AmbiguousBlockAssociation:           # obnoxiously rejects idiomatic Ruby
  Enabled: false

# Naming/FileName is kind of cool but off-base w/r/t demanding that
# Appraisals use snake_case.
#
Naming/FileName:
  Exclude:
    - Appraisals
