sudo: false
language: ruby
before_install:
  - gem install bundler -v 1.14.6
  - gem install rubocop
  - sudo apt-get update -qq
  - sudo apt-get install -qq twemproxy
services:
  - redis-server
rvm:
  - 2.1.6
script:
  - rubocop --version
  - bundle exec rubocop --version
  - bundle exec rubocop
  - bundle exec env REDIS_URL=redis://localhost:6379 rake test
  - nutcracker --test-conf --conf-file=.travis/nutcracker.yml
  - nutcracker             --conf-file=.travis/nutcracker.yml &
  - bundle exec env REDIS_URL=redis://localhost:22121 rake test
