#
# There is no good way to mock Redis's Lua processor, so we test with
# some infrastructure in place.
#
# Also, https://github.com/ProsperWorks/redis-ick/issues/3 revealed issues
# with running over Twemproxy.
#
# We repeat all tests, both connecting directly to Redis and via Twemproxy.
#
sudo:     true
language: ruby
before_install:
  #
  # bundler 2.0.1 requires Ruby version >= 2.3.0 but we still want to
  # support back to 2.2.2.
  #
  # See https://docs.travis-ci.com/user/languages/ruby/#bundler-20 for
  # how this trickery works.
  #
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v 1.16.6
  #
  # We like to prove that redis-ick works via both direct Redis
  # access, but also via Twemproxy.
  #
  - sudo add-apt-repository -y ppa:twemproxy/stable
  - sudo apt-get update -y
  - sudo apt-get install -y twemproxy
services:
  - redis-server
rvm:
  - 2.2.2
  - 2.2.10
  - 2.3.7
  - 2.4.6
  - 2.5.5
  - 2.6.3
gemfile:
  - gemfiles/redis_3.0.gemfile
  - gemfiles/redis_3.1.gemfile
  - gemfiles/redis_3.2.gemfile
  - gemfiles/redis_3.3.gemfile
  - gemfiles/redis_4.0.gemfile
  - gemfiles/redis_4.1.gemfile
script:
  - bundle _1.16.6_ exec rubocop --display-cop-names --display-style-guide
  - bundle _1.16.6_ exec env REDIS_URL=redis://localhost:6379 rake test
before_script:
  - bundle exec rubocop --version
  - nutcracker --version
  - nutcracker --test-conf --conf-file=.travis/nutcracker.yml
  - nutcracker             --conf-file=.travis/nutcracker.yml &
  - sleep 0.3
script:
  - bundle _1.16.6_ exec rubocop --display-cop-names --display-style-guide
  - bundle _1.16.6_ exec env REDIS_URL=redis://localhost:6379 rake test
  - bundle _1.16.6_ exec env REDIS_URL=redis://localhost:22121 rake test
